//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmonicAirline
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveySubmission()
        {
            this.SurveySubmissionDetails = new HashSet<SurveySubmissionDetail>();
        }
    
        public int SurveySubmissionId { get; set; }
        public int SurveyId { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public string CabinType { get; set; }
        public Nullable<int> SubmissionMonth { get; set; }
        public Nullable<int> SubmissionYear { get; set; }
    
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveySubmissionDetail> SurveySubmissionDetails { get; set; }
    }
}
