#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToLookUpLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="arrangeyourtourdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdetailtransaksihotel(detailtransaksihotel instance);
    partial void Updatedetailtransaksihotel(detailtransaksihotel instance);
    partial void Deletedetailtransaksihotel(detailtransaksihotel instance);
    partial void Inserttransaksi(transaksi instance);
    partial void Updatetransaksi(transaksi instance);
    partial void Deletetransaksi(transaksi instance);
    partial void Insertdetailtransaksipenerbangan(detailtransaksipenerbangan instance);
    partial void Updatedetailtransaksipenerbangan(detailtransaksipenerbangan instance);
    partial void Deletedetailtransaksipenerbangan(detailtransaksipenerbangan instance);
    partial void Insertdetailtransaksitour(detailtransaksitour instance);
    partial void Updatedetailtransaksitour(detailtransaksitour instance);
    partial void Deletedetailtransaksitour(detailtransaksitour instance);
    partial void Inserthotel(hotel instance);
    partial void Updatehotel(hotel instance);
    partial void Deletehotel(hotel instance);
    partial void Insertjadwalpenerbangan(jadwalpenerbangan instance);
    partial void Updatejadwalpenerbangan(jadwalpenerbangan instance);
    partial void Deletejadwalpenerbangan(jadwalpenerbangan instance);
    partial void Insertkota(kota instance);
    partial void Updatekota(kota instance);
    partial void Deletekota(kota instance);
    partial void Insertpakettour(pakettour instance);
    partial void Updatepakettour(pakettour instance);
    partial void Deletepakettour(pakettour instance);
    partial void Inserttipekamar(tipekamar instance);
    partial void Updatetipekamar(tipekamar instance);
    partial void Deletetipekamar(tipekamar instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ToLookUpLinq.Properties.Settings.Default.arrangeyourtourdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<detailtransaksihotel> detailtransaksihotels
		{
			get
			{
				return this.GetTable<detailtransaksihotel>();
			}
		}
		
		public System.Data.Linq.Table<transaksi> transaksis
		{
			get
			{
				return this.GetTable<transaksi>();
			}
		}
		
		public System.Data.Linq.Table<detailtransaksipenerbangan> detailtransaksipenerbangans
		{
			get
			{
				return this.GetTable<detailtransaksipenerbangan>();
			}
		}
		
		public System.Data.Linq.Table<detailtransaksitour> detailtransaksitours
		{
			get
			{
				return this.GetTable<detailtransaksitour>();
			}
		}
		
		public System.Data.Linq.Table<hotel> hotels
		{
			get
			{
				return this.GetTable<hotel>();
			}
		}
		
		public System.Data.Linq.Table<jadwalpenerbangan> jadwalpenerbangans
		{
			get
			{
				return this.GetTable<jadwalpenerbangan>();
			}
		}
		
		public System.Data.Linq.Table<kota> kotas
		{
			get
			{
				return this.GetTable<kota>();
			}
		}
		
		public System.Data.Linq.Table<pakettour> pakettours
		{
			get
			{
				return this.GetTable<pakettour>();
			}
		}
		
		public System.Data.Linq.Table<tipekamar> tipekamars
		{
			get
			{
				return this.GetTable<tipekamar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailtransaksihotel")]
	public partial class detailtransaksihotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _idtransaksi;
		
		private System.Nullable<int> _idtipekamar;
		
		private System.Nullable<int> _idhotel;
		
		private System.Nullable<int> _jumlahkamar;
		
		private System.Nullable<int> _hargapermalam;
		
		private System.Nullable<int> _lamatinggal;
		
		private System.Nullable<System.DateTime> _tanggalmasuk;
		
		private System.Nullable<System.DateTime> _tanggalkeluar;
		
		private EntityRef<transaksi> _transaksi;
		
		private EntityRef<hotel> _hotel;
		
		private EntityRef<tipekamar> _tipekamar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnidtransaksiChanging(System.Nullable<int> value);
    partial void OnidtransaksiChanged();
    partial void OnidtipekamarChanging(System.Nullable<int> value);
    partial void OnidtipekamarChanged();
    partial void OnidhotelChanging(System.Nullable<int> value);
    partial void OnidhotelChanged();
    partial void OnjumlahkamarChanging(System.Nullable<int> value);
    partial void OnjumlahkamarChanged();
    partial void OnhargapermalamChanging(System.Nullable<int> value);
    partial void OnhargapermalamChanged();
    partial void OnlamatinggalChanging(System.Nullable<int> value);
    partial void OnlamatinggalChanged();
    partial void OntanggalmasukChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalmasukChanged();
    partial void OntanggalkeluarChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalkeluarChanged();
    #endregion
		
		public detailtransaksihotel()
		{
			this._transaksi = default(EntityRef<transaksi>);
			this._hotel = default(EntityRef<hotel>);
			this._tipekamar = default(EntityRef<tipekamar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtransaksi", DbType="Int")]
		public System.Nullable<int> idtransaksi
		{
			get
			{
				return this._idtransaksi;
			}
			set
			{
				if ((this._idtransaksi != value))
				{
					if (this._transaksi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtransaksiChanging(value);
					this.SendPropertyChanging();
					this._idtransaksi = value;
					this.SendPropertyChanged("idtransaksi");
					this.OnidtransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtipekamar", DbType="Int")]
		public System.Nullable<int> idtipekamar
		{
			get
			{
				return this._idtipekamar;
			}
			set
			{
				if ((this._idtipekamar != value))
				{
					if (this._tipekamar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtipekamarChanging(value);
					this.SendPropertyChanging();
					this._idtipekamar = value;
					this.SendPropertyChanged("idtipekamar");
					this.OnidtipekamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhotel", DbType="Int")]
		public System.Nullable<int> idhotel
		{
			get
			{
				return this._idhotel;
			}
			set
			{
				if ((this._idhotel != value))
				{
					if (this._hotel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidhotelChanging(value);
					this.SendPropertyChanging();
					this._idhotel = value;
					this.SendPropertyChanged("idhotel");
					this.OnidhotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlahkamar", DbType="Int")]
		public System.Nullable<int> jumlahkamar
		{
			get
			{
				return this._jumlahkamar;
			}
			set
			{
				if ((this._jumlahkamar != value))
				{
					this.OnjumlahkamarChanging(value);
					this.SendPropertyChanging();
					this._jumlahkamar = value;
					this.SendPropertyChanged("jumlahkamar");
					this.OnjumlahkamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hargapermalam", DbType="Int")]
		public System.Nullable<int> hargapermalam
		{
			get
			{
				return this._hargapermalam;
			}
			set
			{
				if ((this._hargapermalam != value))
				{
					this.OnhargapermalamChanging(value);
					this.SendPropertyChanging();
					this._hargapermalam = value;
					this.SendPropertyChanged("hargapermalam");
					this.OnhargapermalamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lamatinggal", DbType="Int")]
		public System.Nullable<int> lamatinggal
		{
			get
			{
				return this._lamatinggal;
			}
			set
			{
				if ((this._lamatinggal != value))
				{
					this.OnlamatinggalChanging(value);
					this.SendPropertyChanging();
					this._lamatinggal = value;
					this.SendPropertyChanged("lamatinggal");
					this.OnlamatinggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggalmasuk", DbType="Date")]
		public System.Nullable<System.DateTime> tanggalmasuk
		{
			get
			{
				return this._tanggalmasuk;
			}
			set
			{
				if ((this._tanggalmasuk != value))
				{
					this.OntanggalmasukChanging(value);
					this.SendPropertyChanging();
					this._tanggalmasuk = value;
					this.SendPropertyChanged("tanggalmasuk");
					this.OntanggalmasukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggalkeluar", DbType="Date")]
		public System.Nullable<System.DateTime> tanggalkeluar
		{
			get
			{
				return this._tanggalkeluar;
			}
			set
			{
				if ((this._tanggalkeluar != value))
				{
					this.OntanggalkeluarChanging(value);
					this.SendPropertyChanging();
					this._tanggalkeluar = value;
					this.SendPropertyChanged("tanggalkeluar");
					this.OntanggalkeluarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksihotel", Storage="_transaksi", ThisKey="idtransaksi", OtherKey="idtransaksi", IsForeignKey=true)]
		public transaksi transaksi
		{
			get
			{
				return this._transaksi.Entity;
			}
			set
			{
				transaksi previousValue = this._transaksi.Entity;
				if (((previousValue != value) 
							|| (this._transaksi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._transaksi.Entity = null;
						previousValue.detailtransaksihotels.Remove(this);
					}
					this._transaksi.Entity = value;
					if ((value != null))
					{
						value.detailtransaksihotels.Add(this);
						this._idtransaksi = value.idtransaksi;
					}
					else
					{
						this._idtransaksi = default(Nullable<int>);
					}
					this.SendPropertyChanged("transaksi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_detailtransaksihotel", Storage="_hotel", ThisKey="idhotel", OtherKey="idhotel", IsForeignKey=true)]
		public hotel hotel
		{
			get
			{
				return this._hotel.Entity;
			}
			set
			{
				hotel previousValue = this._hotel.Entity;
				if (((previousValue != value) 
							|| (this._hotel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hotel.Entity = null;
						previousValue.detailtransaksihotels.Remove(this);
					}
					this._hotel.Entity = value;
					if ((value != null))
					{
						value.detailtransaksihotels.Add(this);
						this._idhotel = value.idhotel;
					}
					else
					{
						this._idhotel = default(Nullable<int>);
					}
					this.SendPropertyChanged("hotel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipekamar_detailtransaksihotel", Storage="_tipekamar", ThisKey="idtipekamar", OtherKey="idtipekamar", IsForeignKey=true)]
		public tipekamar tipekamar
		{
			get
			{
				return this._tipekamar.Entity;
			}
			set
			{
				tipekamar previousValue = this._tipekamar.Entity;
				if (((previousValue != value) 
							|| (this._tipekamar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipekamar.Entity = null;
						previousValue.detailtransaksihotels.Remove(this);
					}
					this._tipekamar.Entity = value;
					if ((value != null))
					{
						value.detailtransaksihotels.Add(this);
						this._idtipekamar = value.idtipekamar;
					}
					else
					{
						this._idtipekamar = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipekamar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.transaksi")]
	public partial class transaksi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtransaksi;
		
		private string _namaperjalanan;
		
		private System.Nullable<System.DateTime> _tanggaltransaksi;
		
		private string _email;
		
		private string _status;
		
		private EntitySet<detailtransaksihotel> _detailtransaksihotels;
		
		private EntitySet<detailtransaksipenerbangan> _detailtransaksipenerbangans;
		
		private EntitySet<detailtransaksitour> _detailtransaksitours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtransaksiChanging(int value);
    partial void OnidtransaksiChanged();
    partial void OnnamaperjalananChanging(string value);
    partial void OnnamaperjalananChanged();
    partial void OntanggaltransaksiChanging(System.Nullable<System.DateTime> value);
    partial void OntanggaltransaksiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public transaksi()
		{
			this._detailtransaksihotels = new EntitySet<detailtransaksihotel>(new Action<detailtransaksihotel>(this.attach_detailtransaksihotels), new Action<detailtransaksihotel>(this.detach_detailtransaksihotels));
			this._detailtransaksipenerbangans = new EntitySet<detailtransaksipenerbangan>(new Action<detailtransaksipenerbangan>(this.attach_detailtransaksipenerbangans), new Action<detailtransaksipenerbangan>(this.detach_detailtransaksipenerbangans));
			this._detailtransaksitours = new EntitySet<detailtransaksitour>(new Action<detailtransaksitour>(this.attach_detailtransaksitours), new Action<detailtransaksitour>(this.detach_detailtransaksitours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtransaksi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idtransaksi
		{
			get
			{
				return this._idtransaksi;
			}
			set
			{
				if ((this._idtransaksi != value))
				{
					this.OnidtransaksiChanging(value);
					this.SendPropertyChanging();
					this._idtransaksi = value;
					this.SendPropertyChanged("idtransaksi");
					this.OnidtransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaperjalanan", DbType="VarChar(100)")]
		public string namaperjalanan
		{
			get
			{
				return this._namaperjalanan;
			}
			set
			{
				if ((this._namaperjalanan != value))
				{
					this.OnnamaperjalananChanging(value);
					this.SendPropertyChanging();
					this._namaperjalanan = value;
					this.SendPropertyChanged("namaperjalanan");
					this.OnnamaperjalananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggaltransaksi", DbType="Date")]
		public System.Nullable<System.DateTime> tanggaltransaksi
		{
			get
			{
				return this._tanggaltransaksi;
			}
			set
			{
				if ((this._tanggaltransaksi != value))
				{
					this.OntanggaltransaksiChanging(value);
					this.SendPropertyChanging();
					this._tanggaltransaksi = value;
					this.SendPropertyChanged("tanggaltransaksi");
					this.OntanggaltransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(4)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksihotel", Storage="_detailtransaksihotels", ThisKey="idtransaksi", OtherKey="idtransaksi")]
		public EntitySet<detailtransaksihotel> detailtransaksihotels
		{
			get
			{
				return this._detailtransaksihotels;
			}
			set
			{
				this._detailtransaksihotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksipenerbangan", Storage="_detailtransaksipenerbangans", ThisKey="idtransaksi", OtherKey="idtransaksi")]
		public EntitySet<detailtransaksipenerbangan> detailtransaksipenerbangans
		{
			get
			{
				return this._detailtransaksipenerbangans;
			}
			set
			{
				this._detailtransaksipenerbangans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksitour", Storage="_detailtransaksitours", ThisKey="idtransaksi", OtherKey="idtransaksi")]
		public EntitySet<detailtransaksitour> detailtransaksitours
		{
			get
			{
				return this._detailtransaksitours;
			}
			set
			{
				this._detailtransaksitours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = this;
		}
		
		private void detach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = null;
		}
		
		private void attach_detailtransaksipenerbangans(detailtransaksipenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = this;
		}
		
		private void detach_detailtransaksipenerbangans(detailtransaksipenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = null;
		}
		
		private void attach_detailtransaksitours(detailtransaksitour entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = this;
		}
		
		private void detach_detailtransaksitours(detailtransaksitour entity)
		{
			this.SendPropertyChanging();
			entity.transaksi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailtransaksipenerbangan")]
	public partial class detailtransaksipenerbangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _idtransaksi;
		
		private System.Nullable<int> _idjadwalpenerbangan;
		
		private string _kodepemesanan;
		
		private System.Nullable<int> _hargaperorang;
		
		private System.Nullable<int> _totalpenumpang;
		
		private EntityRef<transaksi> _transaksi;
		
		private EntityRef<jadwalpenerbangan> _jadwalpenerbangan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnidtransaksiChanging(System.Nullable<int> value);
    partial void OnidtransaksiChanged();
    partial void OnidjadwalpenerbanganChanging(System.Nullable<int> value);
    partial void OnidjadwalpenerbanganChanged();
    partial void OnkodepemesananChanging(string value);
    partial void OnkodepemesananChanged();
    partial void OnhargaperorangChanging(System.Nullable<int> value);
    partial void OnhargaperorangChanged();
    partial void OntotalpenumpangChanging(System.Nullable<int> value);
    partial void OntotalpenumpangChanged();
    #endregion
		
		public detailtransaksipenerbangan()
		{
			this._transaksi = default(EntityRef<transaksi>);
			this._jadwalpenerbangan = default(EntityRef<jadwalpenerbangan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtransaksi", DbType="Int")]
		public System.Nullable<int> idtransaksi
		{
			get
			{
				return this._idtransaksi;
			}
			set
			{
				if ((this._idtransaksi != value))
				{
					if (this._transaksi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtransaksiChanging(value);
					this.SendPropertyChanging();
					this._idtransaksi = value;
					this.SendPropertyChanged("idtransaksi");
					this.OnidtransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idjadwalpenerbangan", DbType="Int")]
		public System.Nullable<int> idjadwalpenerbangan
		{
			get
			{
				return this._idjadwalpenerbangan;
			}
			set
			{
				if ((this._idjadwalpenerbangan != value))
				{
					if (this._jadwalpenerbangan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidjadwalpenerbanganChanging(value);
					this.SendPropertyChanging();
					this._idjadwalpenerbangan = value;
					this.SendPropertyChanged("idjadwalpenerbangan");
					this.OnidjadwalpenerbanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodepemesanan", DbType="Char(8)")]
		public string kodepemesanan
		{
			get
			{
				return this._kodepemesanan;
			}
			set
			{
				if ((this._kodepemesanan != value))
				{
					this.OnkodepemesananChanging(value);
					this.SendPropertyChanging();
					this._kodepemesanan = value;
					this.SendPropertyChanged("kodepemesanan");
					this.OnkodepemesananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hargaperorang", DbType="Int")]
		public System.Nullable<int> hargaperorang
		{
			get
			{
				return this._hargaperorang;
			}
			set
			{
				if ((this._hargaperorang != value))
				{
					this.OnhargaperorangChanging(value);
					this.SendPropertyChanging();
					this._hargaperorang = value;
					this.SendPropertyChanged("hargaperorang");
					this.OnhargaperorangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalpenumpang", DbType="Int")]
		public System.Nullable<int> totalpenumpang
		{
			get
			{
				return this._totalpenumpang;
			}
			set
			{
				if ((this._totalpenumpang != value))
				{
					this.OntotalpenumpangChanging(value);
					this.SendPropertyChanging();
					this._totalpenumpang = value;
					this.SendPropertyChanged("totalpenumpang");
					this.OntotalpenumpangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksipenerbangan", Storage="_transaksi", ThisKey="idtransaksi", OtherKey="idtransaksi", IsForeignKey=true)]
		public transaksi transaksi
		{
			get
			{
				return this._transaksi.Entity;
			}
			set
			{
				transaksi previousValue = this._transaksi.Entity;
				if (((previousValue != value) 
							|| (this._transaksi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._transaksi.Entity = null;
						previousValue.detailtransaksipenerbangans.Remove(this);
					}
					this._transaksi.Entity = value;
					if ((value != null))
					{
						value.detailtransaksipenerbangans.Add(this);
						this._idtransaksi = value.idtransaksi;
					}
					else
					{
						this._idtransaksi = default(Nullable<int>);
					}
					this.SendPropertyChanged("transaksi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jadwalpenerbangan_detailtransaksipenerbangan", Storage="_jadwalpenerbangan", ThisKey="idjadwalpenerbangan", OtherKey="idjadwalpenerbangan", IsForeignKey=true)]
		public jadwalpenerbangan jadwalpenerbangan
		{
			get
			{
				return this._jadwalpenerbangan.Entity;
			}
			set
			{
				jadwalpenerbangan previousValue = this._jadwalpenerbangan.Entity;
				if (((previousValue != value) 
							|| (this._jadwalpenerbangan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jadwalpenerbangan.Entity = null;
						previousValue.detailtransaksipenerbangans.Remove(this);
					}
					this._jadwalpenerbangan.Entity = value;
					if ((value != null))
					{
						value.detailtransaksipenerbangans.Add(this);
						this._idjadwalpenerbangan = value.idjadwalpenerbangan;
					}
					else
					{
						this._idjadwalpenerbangan = default(Nullable<int>);
					}
					this.SendPropertyChanged("jadwalpenerbangan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailtransaksitour")]
	public partial class detailtransaksitour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _idtransaksi;
		
		private System.Nullable<int> _idpakettour;
		
		private System.Nullable<int> _totalpengunjung;
		
		private System.Nullable<int> _harga;
		
		private System.Nullable<System.DateTime> _tanggalmasuk;
		
		private EntityRef<transaksi> _transaksi;
		
		private EntityRef<pakettour> _pakettour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnidtransaksiChanging(System.Nullable<int> value);
    partial void OnidtransaksiChanged();
    partial void OnidpakettourChanging(System.Nullable<int> value);
    partial void OnidpakettourChanged();
    partial void OntotalpengunjungChanging(System.Nullable<int> value);
    partial void OntotalpengunjungChanged();
    partial void OnhargaChanging(System.Nullable<int> value);
    partial void OnhargaChanged();
    partial void OntanggalmasukChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalmasukChanged();
    #endregion
		
		public detailtransaksitour()
		{
			this._transaksi = default(EntityRef<transaksi>);
			this._pakettour = default(EntityRef<pakettour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtransaksi", DbType="Int")]
		public System.Nullable<int> idtransaksi
		{
			get
			{
				return this._idtransaksi;
			}
			set
			{
				if ((this._idtransaksi != value))
				{
					if (this._transaksi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtransaksiChanging(value);
					this.SendPropertyChanging();
					this._idtransaksi = value;
					this.SendPropertyChanged("idtransaksi");
					this.OnidtransaksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpakettour", DbType="Int")]
		public System.Nullable<int> idpakettour
		{
			get
			{
				return this._idpakettour;
			}
			set
			{
				if ((this._idpakettour != value))
				{
					if (this._pakettour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidpakettourChanging(value);
					this.SendPropertyChanging();
					this._idpakettour = value;
					this.SendPropertyChanged("idpakettour");
					this.OnidpakettourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalpengunjung", DbType="Int")]
		public System.Nullable<int> totalpengunjung
		{
			get
			{
				return this._totalpengunjung;
			}
			set
			{
				if ((this._totalpengunjung != value))
				{
					this.OntotalpengunjungChanging(value);
					this.SendPropertyChanging();
					this._totalpengunjung = value;
					this.SendPropertyChanged("totalpengunjung");
					this.OntotalpengunjungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int")]
		public System.Nullable<int> harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggalmasuk", DbType="Date")]
		public System.Nullable<System.DateTime> tanggalmasuk
		{
			get
			{
				return this._tanggalmasuk;
			}
			set
			{
				if ((this._tanggalmasuk != value))
				{
					this.OntanggalmasukChanging(value);
					this.SendPropertyChanging();
					this._tanggalmasuk = value;
					this.SendPropertyChanged("tanggalmasuk");
					this.OntanggalmasukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="transaksi_detailtransaksitour", Storage="_transaksi", ThisKey="idtransaksi", OtherKey="idtransaksi", IsForeignKey=true)]
		public transaksi transaksi
		{
			get
			{
				return this._transaksi.Entity;
			}
			set
			{
				transaksi previousValue = this._transaksi.Entity;
				if (((previousValue != value) 
							|| (this._transaksi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._transaksi.Entity = null;
						previousValue.detailtransaksitours.Remove(this);
					}
					this._transaksi.Entity = value;
					if ((value != null))
					{
						value.detailtransaksitours.Add(this);
						this._idtransaksi = value.idtransaksi;
					}
					else
					{
						this._idtransaksi = default(Nullable<int>);
					}
					this.SendPropertyChanged("transaksi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pakettour_detailtransaksitour", Storage="_pakettour", ThisKey="idpakettour", OtherKey="idpakettour", IsForeignKey=true)]
		public pakettour pakettour
		{
			get
			{
				return this._pakettour.Entity;
			}
			set
			{
				pakettour previousValue = this._pakettour.Entity;
				if (((previousValue != value) 
							|| (this._pakettour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pakettour.Entity = null;
						previousValue.detailtransaksitours.Remove(this);
					}
					this._pakettour.Entity = value;
					if ((value != null))
					{
						value.detailtransaksitours.Add(this);
						this._idpakettour = value.idpakettour;
					}
					else
					{
						this._idpakettour = default(Nullable<int>);
					}
					this.SendPropertyChanged("pakettour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hotel")]
	public partial class hotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idhotel;
		
		private string _namahotel;
		
		private System.Nullable<int> _idkota;
		
		private EntitySet<detailtransaksihotel> _detailtransaksihotels;
		
		private EntitySet<tipekamar> _tipekamars;
		
		private EntityRef<kota> _kota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidhotelChanging(int value);
    partial void OnidhotelChanged();
    partial void OnnamahotelChanging(string value);
    partial void OnnamahotelChanged();
    partial void OnidkotaChanging(System.Nullable<int> value);
    partial void OnidkotaChanged();
    #endregion
		
		public hotel()
		{
			this._detailtransaksihotels = new EntitySet<detailtransaksihotel>(new Action<detailtransaksihotel>(this.attach_detailtransaksihotels), new Action<detailtransaksihotel>(this.detach_detailtransaksihotels));
			this._tipekamars = new EntitySet<tipekamar>(new Action<tipekamar>(this.attach_tipekamars), new Action<tipekamar>(this.detach_tipekamars));
			this._kota = default(EntityRef<kota>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhotel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idhotel
		{
			get
			{
				return this._idhotel;
			}
			set
			{
				if ((this._idhotel != value))
				{
					this.OnidhotelChanging(value);
					this.SendPropertyChanging();
					this._idhotel = value;
					this.SendPropertyChanged("idhotel");
					this.OnidhotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namahotel", DbType="VarChar(100)")]
		public string namahotel
		{
			get
			{
				return this._namahotel;
			}
			set
			{
				if ((this._namahotel != value))
				{
					this.OnnamahotelChanging(value);
					this.SendPropertyChanging();
					this._namahotel = value;
					this.SendPropertyChanged("namahotel");
					this.OnnamahotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkota", DbType="Int")]
		public System.Nullable<int> idkota
		{
			get
			{
				return this._idkota;
			}
			set
			{
				if ((this._idkota != value))
				{
					if (this._kota.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidkotaChanging(value);
					this.SendPropertyChanging();
					this._idkota = value;
					this.SendPropertyChanged("idkota");
					this.OnidkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_detailtransaksihotel", Storage="_detailtransaksihotels", ThisKey="idhotel", OtherKey="idhotel")]
		public EntitySet<detailtransaksihotel> detailtransaksihotels
		{
			get
			{
				return this._detailtransaksihotels;
			}
			set
			{
				this._detailtransaksihotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_tipekamar", Storage="_tipekamars", ThisKey="idhotel", OtherKey="idhotel")]
		public EntitySet<tipekamar> tipekamars
		{
			get
			{
				return this._tipekamars;
			}
			set
			{
				this._tipekamars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_hotel", Storage="_kota", ThisKey="idkota", OtherKey="idkota", IsForeignKey=true)]
		public kota kota
		{
			get
			{
				return this._kota.Entity;
			}
			set
			{
				kota previousValue = this._kota.Entity;
				if (((previousValue != value) 
							|| (this._kota.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kota.Entity = null;
						previousValue.hotels.Remove(this);
					}
					this._kota.Entity = value;
					if ((value != null))
					{
						value.hotels.Add(this);
						this._idkota = value.idkota;
					}
					else
					{
						this._idkota = default(Nullable<int>);
					}
					this.SendPropertyChanged("kota");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.hotel = this;
		}
		
		private void detach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.hotel = null;
		}
		
		private void attach_tipekamars(tipekamar entity)
		{
			this.SendPropertyChanging();
			entity.hotel = this;
		}
		
		private void detach_tipekamars(tipekamar entity)
		{
			this.SendPropertyChanging();
			entity.hotel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jadwalpenerbangan")]
	public partial class jadwalpenerbangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idjadwalpenerbangan;
		
		private System.Nullable<int> _idkotakeberangkatan;
		
		private System.Nullable<int> _idkotatujuan;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private System.Nullable<int> _kapasitas;
		
		private System.Nullable<System.TimeSpan> _waktupenerbangan;
		
		private System.Nullable<int> _biayaperjalanan;
		
		private EntitySet<detailtransaksipenerbangan> _detailtransaksipenerbangans;
		
		private EntityRef<kota> _kota;
		
		private EntityRef<kota> _kota1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidjadwalpenerbanganChanging(int value);
    partial void OnidjadwalpenerbanganChanged();
    partial void OnidkotakeberangkatanChanging(System.Nullable<int> value);
    partial void OnidkotakeberangkatanChanged();
    partial void OnidkotatujuanChanging(System.Nullable<int> value);
    partial void OnidkotatujuanChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnkapasitasChanging(System.Nullable<int> value);
    partial void OnkapasitasChanged();
    partial void OnwaktupenerbanganChanging(System.Nullable<System.TimeSpan> value);
    partial void OnwaktupenerbanganChanged();
    partial void OnbiayaperjalananChanging(System.Nullable<int> value);
    partial void OnbiayaperjalananChanged();
    #endregion
		
		public jadwalpenerbangan()
		{
			this._detailtransaksipenerbangans = new EntitySet<detailtransaksipenerbangan>(new Action<detailtransaksipenerbangan>(this.attach_detailtransaksipenerbangans), new Action<detailtransaksipenerbangan>(this.detach_detailtransaksipenerbangans));
			this._kota = default(EntityRef<kota>);
			this._kota1 = default(EntityRef<kota>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idjadwalpenerbangan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idjadwalpenerbangan
		{
			get
			{
				return this._idjadwalpenerbangan;
			}
			set
			{
				if ((this._idjadwalpenerbangan != value))
				{
					this.OnidjadwalpenerbanganChanging(value);
					this.SendPropertyChanging();
					this._idjadwalpenerbangan = value;
					this.SendPropertyChanged("idjadwalpenerbangan");
					this.OnidjadwalpenerbanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkotakeberangkatan", DbType="Int")]
		public System.Nullable<int> idkotakeberangkatan
		{
			get
			{
				return this._idkotakeberangkatan;
			}
			set
			{
				if ((this._idkotakeberangkatan != value))
				{
					if (this._kota.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidkotakeberangkatanChanging(value);
					this.SendPropertyChanging();
					this._idkotakeberangkatan = value;
					this.SendPropertyChanged("idkotakeberangkatan");
					this.OnidkotakeberangkatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkotatujuan", DbType="Int")]
		public System.Nullable<int> idkotatujuan
		{
			get
			{
				return this._idkotatujuan;
			}
			set
			{
				if ((this._idkotatujuan != value))
				{
					if (this._kota1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidkotatujuanChanging(value);
					this.SendPropertyChanging();
					this._idkotatujuan = value;
					this.SendPropertyChanged("idkotatujuan");
					this.OnidkotatujuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kapasitas", DbType="Int")]
		public System.Nullable<int> kapasitas
		{
			get
			{
				return this._kapasitas;
			}
			set
			{
				if ((this._kapasitas != value))
				{
					this.OnkapasitasChanging(value);
					this.SendPropertyChanging();
					this._kapasitas = value;
					this.SendPropertyChanged("kapasitas");
					this.OnkapasitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waktupenerbangan", DbType="Time")]
		public System.Nullable<System.TimeSpan> waktupenerbangan
		{
			get
			{
				return this._waktupenerbangan;
			}
			set
			{
				if ((this._waktupenerbangan != value))
				{
					this.OnwaktupenerbanganChanging(value);
					this.SendPropertyChanging();
					this._waktupenerbangan = value;
					this.SendPropertyChanged("waktupenerbangan");
					this.OnwaktupenerbanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biayaperjalanan", DbType="Int")]
		public System.Nullable<int> biayaperjalanan
		{
			get
			{
				return this._biayaperjalanan;
			}
			set
			{
				if ((this._biayaperjalanan != value))
				{
					this.OnbiayaperjalananChanging(value);
					this.SendPropertyChanging();
					this._biayaperjalanan = value;
					this.SendPropertyChanged("biayaperjalanan");
					this.OnbiayaperjalananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jadwalpenerbangan_detailtransaksipenerbangan", Storage="_detailtransaksipenerbangans", ThisKey="idjadwalpenerbangan", OtherKey="idjadwalpenerbangan")]
		public EntitySet<detailtransaksipenerbangan> detailtransaksipenerbangans
		{
			get
			{
				return this._detailtransaksipenerbangans;
			}
			set
			{
				this._detailtransaksipenerbangans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_jadwalpenerbangan", Storage="_kota", ThisKey="idkotakeberangkatan", OtherKey="idkota", IsForeignKey=true)]
		public kota kota
		{
			get
			{
				return this._kota.Entity;
			}
			set
			{
				kota previousValue = this._kota.Entity;
				if (((previousValue != value) 
							|| (this._kota.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kota.Entity = null;
						previousValue.jadwalpenerbangans.Remove(this);
					}
					this._kota.Entity = value;
					if ((value != null))
					{
						value.jadwalpenerbangans.Add(this);
						this._idkotakeberangkatan = value.idkota;
					}
					else
					{
						this._idkotakeberangkatan = default(Nullable<int>);
					}
					this.SendPropertyChanged("kota");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_jadwalpenerbangan1", Storage="_kota1", ThisKey="idkotatujuan", OtherKey="idkota", IsForeignKey=true)]
		public kota kota1
		{
			get
			{
				return this._kota1.Entity;
			}
			set
			{
				kota previousValue = this._kota1.Entity;
				if (((previousValue != value) 
							|| (this._kota1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kota1.Entity = null;
						previousValue.jadwalpenerbangans1.Remove(this);
					}
					this._kota1.Entity = value;
					if ((value != null))
					{
						value.jadwalpenerbangans1.Add(this);
						this._idkotatujuan = value.idkota;
					}
					else
					{
						this._idkotatujuan = default(Nullable<int>);
					}
					this.SendPropertyChanged("kota1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailtransaksipenerbangans(detailtransaksipenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.jadwalpenerbangan = this;
		}
		
		private void detach_detailtransaksipenerbangans(detailtransaksipenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.jadwalpenerbangan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kota")]
	public partial class kota : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idkota;
		
		private string _namakota;
		
		private EntitySet<hotel> _hotels;
		
		private EntitySet<jadwalpenerbangan> _jadwalpenerbangans;
		
		private EntitySet<jadwalpenerbangan> _jadwalpenerbangans1;
		
		private EntitySet<pakettour> _pakettours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidkotaChanging(int value);
    partial void OnidkotaChanged();
    partial void OnnamakotaChanging(string value);
    partial void OnnamakotaChanged();
    #endregion
		
		public kota()
		{
			this._hotels = new EntitySet<hotel>(new Action<hotel>(this.attach_hotels), new Action<hotel>(this.detach_hotels));
			this._jadwalpenerbangans = new EntitySet<jadwalpenerbangan>(new Action<jadwalpenerbangan>(this.attach_jadwalpenerbangans), new Action<jadwalpenerbangan>(this.detach_jadwalpenerbangans));
			this._jadwalpenerbangans1 = new EntitySet<jadwalpenerbangan>(new Action<jadwalpenerbangan>(this.attach_jadwalpenerbangans1), new Action<jadwalpenerbangan>(this.detach_jadwalpenerbangans1));
			this._pakettours = new EntitySet<pakettour>(new Action<pakettour>(this.attach_pakettours), new Action<pakettour>(this.detach_pakettours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idkota
		{
			get
			{
				return this._idkota;
			}
			set
			{
				if ((this._idkota != value))
				{
					this.OnidkotaChanging(value);
					this.SendPropertyChanging();
					this._idkota = value;
					this.SendPropertyChanged("idkota");
					this.OnidkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namakota", DbType="VarChar(100)")]
		public string namakota
		{
			get
			{
				return this._namakota;
			}
			set
			{
				if ((this._namakota != value))
				{
					this.OnnamakotaChanging(value);
					this.SendPropertyChanging();
					this._namakota = value;
					this.SendPropertyChanged("namakota");
					this.OnnamakotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_hotel", Storage="_hotels", ThisKey="idkota", OtherKey="idkota")]
		public EntitySet<hotel> hotels
		{
			get
			{
				return this._hotels;
			}
			set
			{
				this._hotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_jadwalpenerbangan", Storage="_jadwalpenerbangans", ThisKey="idkota", OtherKey="idkotakeberangkatan")]
		public EntitySet<jadwalpenerbangan> jadwalpenerbangans
		{
			get
			{
				return this._jadwalpenerbangans;
			}
			set
			{
				this._jadwalpenerbangans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_jadwalpenerbangan1", Storage="_jadwalpenerbangans1", ThisKey="idkota", OtherKey="idkotatujuan")]
		public EntitySet<jadwalpenerbangan> jadwalpenerbangans1
		{
			get
			{
				return this._jadwalpenerbangans1;
			}
			set
			{
				this._jadwalpenerbangans1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_pakettour", Storage="_pakettours", ThisKey="idkota", OtherKey="idkota")]
		public EntitySet<pakettour> pakettours
		{
			get
			{
				return this._pakettours;
			}
			set
			{
				this._pakettours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hotels(hotel entity)
		{
			this.SendPropertyChanging();
			entity.kota = this;
		}
		
		private void detach_hotels(hotel entity)
		{
			this.SendPropertyChanging();
			entity.kota = null;
		}
		
		private void attach_jadwalpenerbangans(jadwalpenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.kota = this;
		}
		
		private void detach_jadwalpenerbangans(jadwalpenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.kota = null;
		}
		
		private void attach_jadwalpenerbangans1(jadwalpenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.kota1 = this;
		}
		
		private void detach_jadwalpenerbangans1(jadwalpenerbangan entity)
		{
			this.SendPropertyChanging();
			entity.kota1 = null;
		}
		
		private void attach_pakettours(pakettour entity)
		{
			this.SendPropertyChanging();
			entity.kota = this;
		}
		
		private void detach_pakettours(pakettour entity)
		{
			this.SendPropertyChanging();
			entity.kota = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pakettour")]
	public partial class pakettour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idpakettour;
		
		private System.Nullable<int> _idkota;
		
		private string _harimulaibuka;
		
		private string _hariterakhirbuka;
		
		private System.Nullable<int> _biaya;
		
		private System.Nullable<int> _kapasitaspeserta;
		
		private string _namapaket;
		
		private EntitySet<detailtransaksitour> _detailtransaksitours;
		
		private EntityRef<kota> _kota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidpakettourChanging(int value);
    partial void OnidpakettourChanged();
    partial void OnidkotaChanging(System.Nullable<int> value);
    partial void OnidkotaChanged();
    partial void OnharimulaibukaChanging(string value);
    partial void OnharimulaibukaChanged();
    partial void OnhariterakhirbukaChanging(string value);
    partial void OnhariterakhirbukaChanged();
    partial void OnbiayaChanging(System.Nullable<int> value);
    partial void OnbiayaChanged();
    partial void OnkapasitaspesertaChanging(System.Nullable<int> value);
    partial void OnkapasitaspesertaChanged();
    partial void OnnamapaketChanging(string value);
    partial void OnnamapaketChanged();
    #endregion
		
		public pakettour()
		{
			this._detailtransaksitours = new EntitySet<detailtransaksitour>(new Action<detailtransaksitour>(this.attach_detailtransaksitours), new Action<detailtransaksitour>(this.detach_detailtransaksitours));
			this._kota = default(EntityRef<kota>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpakettour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idpakettour
		{
			get
			{
				return this._idpakettour;
			}
			set
			{
				if ((this._idpakettour != value))
				{
					this.OnidpakettourChanging(value);
					this.SendPropertyChanging();
					this._idpakettour = value;
					this.SendPropertyChanged("idpakettour");
					this.OnidpakettourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkota", DbType="Int")]
		public System.Nullable<int> idkota
		{
			get
			{
				return this._idkota;
			}
			set
			{
				if ((this._idkota != value))
				{
					if (this._kota.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidkotaChanging(value);
					this.SendPropertyChanging();
					this._idkota = value;
					this.SendPropertyChanged("idkota");
					this.OnidkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harimulaibuka", DbType="VarChar(20)")]
		public string harimulaibuka
		{
			get
			{
				return this._harimulaibuka;
			}
			set
			{
				if ((this._harimulaibuka != value))
				{
					this.OnharimulaibukaChanging(value);
					this.SendPropertyChanging();
					this._harimulaibuka = value;
					this.SendPropertyChanged("harimulaibuka");
					this.OnharimulaibukaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hariterakhirbuka", DbType="VarChar(20)")]
		public string hariterakhirbuka
		{
			get
			{
				return this._hariterakhirbuka;
			}
			set
			{
				if ((this._hariterakhirbuka != value))
				{
					this.OnhariterakhirbukaChanging(value);
					this.SendPropertyChanging();
					this._hariterakhirbuka = value;
					this.SendPropertyChanged("hariterakhirbuka");
					this.OnhariterakhirbukaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biaya", DbType="Int")]
		public System.Nullable<int> biaya
		{
			get
			{
				return this._biaya;
			}
			set
			{
				if ((this._biaya != value))
				{
					this.OnbiayaChanging(value);
					this.SendPropertyChanging();
					this._biaya = value;
					this.SendPropertyChanged("biaya");
					this.OnbiayaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kapasitaspeserta", DbType="Int")]
		public System.Nullable<int> kapasitaspeserta
		{
			get
			{
				return this._kapasitaspeserta;
			}
			set
			{
				if ((this._kapasitaspeserta != value))
				{
					this.OnkapasitaspesertaChanging(value);
					this.SendPropertyChanging();
					this._kapasitaspeserta = value;
					this.SendPropertyChanged("kapasitaspeserta");
					this.OnkapasitaspesertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namapaket", DbType="VarChar(100)")]
		public string namapaket
		{
			get
			{
				return this._namapaket;
			}
			set
			{
				if ((this._namapaket != value))
				{
					this.OnnamapaketChanging(value);
					this.SendPropertyChanging();
					this._namapaket = value;
					this.SendPropertyChanged("namapaket");
					this.OnnamapaketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pakettour_detailtransaksitour", Storage="_detailtransaksitours", ThisKey="idpakettour", OtherKey="idpakettour")]
		public EntitySet<detailtransaksitour> detailtransaksitours
		{
			get
			{
				return this._detailtransaksitours;
			}
			set
			{
				this._detailtransaksitours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kota_pakettour", Storage="_kota", ThisKey="idkota", OtherKey="idkota", IsForeignKey=true)]
		public kota kota
		{
			get
			{
				return this._kota.Entity;
			}
			set
			{
				kota previousValue = this._kota.Entity;
				if (((previousValue != value) 
							|| (this._kota.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kota.Entity = null;
						previousValue.pakettours.Remove(this);
					}
					this._kota.Entity = value;
					if ((value != null))
					{
						value.pakettours.Add(this);
						this._idkota = value.idkota;
					}
					else
					{
						this._idkota = default(Nullable<int>);
					}
					this.SendPropertyChanged("kota");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailtransaksitours(detailtransaksitour entity)
		{
			this.SendPropertyChanging();
			entity.pakettour = this;
		}
		
		private void detach_detailtransaksitours(detailtransaksitour entity)
		{
			this.SendPropertyChanging();
			entity.pakettour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipekamar")]
	public partial class tipekamar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtipekamar;
		
		private System.Nullable<int> _idhotel;
		
		private string _namatipekamar;
		
		private System.Nullable<int> _hargapermalam;
		
		private System.Nullable<int> _jumlahkamar;
		
		private EntitySet<detailtransaksihotel> _detailtransaksihotels;
		
		private EntityRef<hotel> _hotel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtipekamarChanging(int value);
    partial void OnidtipekamarChanged();
    partial void OnidhotelChanging(System.Nullable<int> value);
    partial void OnidhotelChanged();
    partial void OnnamatipekamarChanging(string value);
    partial void OnnamatipekamarChanged();
    partial void OnhargapermalamChanging(System.Nullable<int> value);
    partial void OnhargapermalamChanged();
    partial void OnjumlahkamarChanging(System.Nullable<int> value);
    partial void OnjumlahkamarChanged();
    #endregion
		
		public tipekamar()
		{
			this._detailtransaksihotels = new EntitySet<detailtransaksihotel>(new Action<detailtransaksihotel>(this.attach_detailtransaksihotels), new Action<detailtransaksihotel>(this.detach_detailtransaksihotels));
			this._hotel = default(EntityRef<hotel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtipekamar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idtipekamar
		{
			get
			{
				return this._idtipekamar;
			}
			set
			{
				if ((this._idtipekamar != value))
				{
					this.OnidtipekamarChanging(value);
					this.SendPropertyChanging();
					this._idtipekamar = value;
					this.SendPropertyChanged("idtipekamar");
					this.OnidtipekamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhotel", DbType="Int")]
		public System.Nullable<int> idhotel
		{
			get
			{
				return this._idhotel;
			}
			set
			{
				if ((this._idhotel != value))
				{
					if (this._hotel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidhotelChanging(value);
					this.SendPropertyChanging();
					this._idhotel = value;
					this.SendPropertyChanged("idhotel");
					this.OnidhotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namatipekamar", DbType="VarChar(100)")]
		public string namatipekamar
		{
			get
			{
				return this._namatipekamar;
			}
			set
			{
				if ((this._namatipekamar != value))
				{
					this.OnnamatipekamarChanging(value);
					this.SendPropertyChanging();
					this._namatipekamar = value;
					this.SendPropertyChanged("namatipekamar");
					this.OnnamatipekamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hargapermalam", DbType="Int")]
		public System.Nullable<int> hargapermalam
		{
			get
			{
				return this._hargapermalam;
			}
			set
			{
				if ((this._hargapermalam != value))
				{
					this.OnhargapermalamChanging(value);
					this.SendPropertyChanging();
					this._hargapermalam = value;
					this.SendPropertyChanged("hargapermalam");
					this.OnhargapermalamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlahkamar", DbType="Int")]
		public System.Nullable<int> jumlahkamar
		{
			get
			{
				return this._jumlahkamar;
			}
			set
			{
				if ((this._jumlahkamar != value))
				{
					this.OnjumlahkamarChanging(value);
					this.SendPropertyChanging();
					this._jumlahkamar = value;
					this.SendPropertyChanged("jumlahkamar");
					this.OnjumlahkamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipekamar_detailtransaksihotel", Storage="_detailtransaksihotels", ThisKey="idtipekamar", OtherKey="idtipekamar")]
		public EntitySet<detailtransaksihotel> detailtransaksihotels
		{
			get
			{
				return this._detailtransaksihotels;
			}
			set
			{
				this._detailtransaksihotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_tipekamar", Storage="_hotel", ThisKey="idhotel", OtherKey="idhotel", IsForeignKey=true)]
		public hotel hotel
		{
			get
			{
				return this._hotel.Entity;
			}
			set
			{
				hotel previousValue = this._hotel.Entity;
				if (((previousValue != value) 
							|| (this._hotel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hotel.Entity = null;
						previousValue.tipekamars.Remove(this);
					}
					this._hotel.Entity = value;
					if ((value != null))
					{
						value.tipekamars.Add(this);
						this._idhotel = value.idhotel;
					}
					else
					{
						this._idhotel = default(Nullable<int>);
					}
					this.SendPropertyChanged("hotel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.tipekamar = this;
		}
		
		private void detach_detailtransaksihotels(detailtransaksihotel entity)
		{
			this.SendPropertyChanging();
			entity.tipekamar = null;
		}
	}
}
#pragma warning restore 1591
