#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Modul01-Hengky")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdetaildelivery(detaildelivery instance);
    partial void Updatedetaildelivery(detaildelivery instance);
    partial void Deletedetaildelivery(detaildelivery instance);
    partial void Insertmsproduk(msproduk instance);
    partial void Updatemsproduk(msproduk instance);
    partial void Deletemsproduk(msproduk instance);
    partial void Insertdetailfaktur(detailfaktur instance);
    partial void Updatedetailfaktur(detailfaktur instance);
    partial void Deletedetailfaktur(detailfaktur instance);
    partial void Insertheaderdelivery(headerdelivery instance);
    partial void Updateheaderdelivery(headerdelivery instance);
    partial void Deleteheaderdelivery(headerdelivery instance);
    partial void Insertheaderfaktur(headerfaktur instance);
    partial void Updateheaderfaktur(headerfaktur instance);
    partial void Deleteheaderfaktur(headerfaktur instance);
    partial void Insertheaderpo(headerpo instance);
    partial void Updateheaderpo(headerpo instance);
    partial void Deleteheaderpo(headerpo instance);
    partial void Insertmscustomer(mscustomer instance);
    partial void Updatemscustomer(mscustomer instance);
    partial void Deletemscustomer(mscustomer instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LINQ.Properties.Settings.Default.Modul01_HengkyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<detaildelivery> detaildeliveries
		{
			get
			{
				return this.GetTable<detaildelivery>();
			}
		}
		
		public System.Data.Linq.Table<msproduk> msproduks
		{
			get
			{
				return this.GetTable<msproduk>();
			}
		}
		
		public System.Data.Linq.Table<detailfaktur> detailfakturs
		{
			get
			{
				return this.GetTable<detailfaktur>();
			}
		}
		
		public System.Data.Linq.Table<headerdelivery> headerdeliveries
		{
			get
			{
				return this.GetTable<headerdelivery>();
			}
		}
		
		public System.Data.Linq.Table<headerfaktur> headerfakturs
		{
			get
			{
				return this.GetTable<headerfaktur>();
			}
		}
		
		public System.Data.Linq.Table<headerpo> headerpos
		{
			get
			{
				return this.GetTable<headerpo>();
			}
		}
		
		public System.Data.Linq.Table<mscustomer> mscustomers
		{
			get
			{
				return this.GetTable<mscustomer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detaildelivery")]
	public partial class detaildelivery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _detaildeliveryid;
		
		private string _deliveryid;
		
		private string _productid;
		
		private System.Nullable<int> _qty;
		
		private EntityRef<msproduk> _msproduk;
		
		private EntityRef<headerdelivery> _headerdelivery;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndetaildeliveryidChanging(int value);
    partial void OndetaildeliveryidChanged();
    partial void OndeliveryidChanging(string value);
    partial void OndeliveryidChanged();
    partial void OnproductidChanging(string value);
    partial void OnproductidChanged();
    partial void OnqtyChanging(System.Nullable<int> value);
    partial void OnqtyChanged();
    #endregion
		
		public detaildelivery()
		{
			this._msproduk = default(EntityRef<msproduk>);
			this._headerdelivery = default(EntityRef<headerdelivery>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detaildeliveryid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int detaildeliveryid
		{
			get
			{
				return this._detaildeliveryid;
			}
			set
			{
				if ((this._detaildeliveryid != value))
				{
					this.OndetaildeliveryidChanging(value);
					this.SendPropertyChanging();
					this._detaildeliveryid = value;
					this.SendPropertyChanged("detaildeliveryid");
					this.OndetaildeliveryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliveryid", DbType="NChar(8)")]
		public string deliveryid
		{
			get
			{
				return this._deliveryid;
			}
			set
			{
				if ((this._deliveryid != value))
				{
					if (this._headerdelivery.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndeliveryidChanging(value);
					this.SendPropertyChanging();
					this._deliveryid = value;
					this.SendPropertyChanged("deliveryid");
					this.OndeliveryidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", DbType="NChar(5)")]
		public string productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					if (this._msproduk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductidChanging(value);
					this.SendPropertyChanging();
					this._productid = value;
					this.SendPropertyChanged("productid");
					this.OnproductidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
		public System.Nullable<int> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="msproduk_detaildelivery", Storage="_msproduk", ThisKey="productid", OtherKey="productid", IsForeignKey=true)]
		public msproduk msproduk
		{
			get
			{
				return this._msproduk.Entity;
			}
			set
			{
				msproduk previousValue = this._msproduk.Entity;
				if (((previousValue != value) 
							|| (this._msproduk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._msproduk.Entity = null;
						previousValue.detaildeliveries.Remove(this);
					}
					this._msproduk.Entity = value;
					if ((value != null))
					{
						value.detaildeliveries.Add(this);
						this._productid = value.productid;
					}
					else
					{
						this._productid = default(string);
					}
					this.SendPropertyChanged("msproduk");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerdelivery_detaildelivery", Storage="_headerdelivery", ThisKey="deliveryid", OtherKey="DeliveryId", IsForeignKey=true)]
		public headerdelivery headerdelivery
		{
			get
			{
				return this._headerdelivery.Entity;
			}
			set
			{
				headerdelivery previousValue = this._headerdelivery.Entity;
				if (((previousValue != value) 
							|| (this._headerdelivery.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._headerdelivery.Entity = null;
						previousValue.detaildeliveries.Remove(this);
					}
					this._headerdelivery.Entity = value;
					if ((value != null))
					{
						value.detaildeliveries.Add(this);
						this._deliveryid = value.DeliveryId;
					}
					else
					{
						this._deliveryid = default(string);
					}
					this.SendPropertyChanged("headerdelivery");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.msproduk")]
	public partial class msproduk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _productid;
		
		private string _name;
		
		private string _packaging;
		
		private System.Nullable<int> _price;
		
		private EntitySet<detaildelivery> _detaildeliveries;
		
		private EntitySet<detailfaktur> _detailfakturs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductidChanging(string value);
    partial void OnproductidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpackagingChanging(string value);
    partial void OnpackagingChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public msproduk()
		{
			this._detaildeliveries = new EntitySet<detaildelivery>(new Action<detaildelivery>(this.attach_detaildeliveries), new Action<detaildelivery>(this.detach_detaildeliveries));
			this._detailfakturs = new EntitySet<detailfaktur>(new Action<detailfaktur>(this.attach_detailfakturs), new Action<detailfaktur>(this.detach_detailfakturs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					this.OnproductidChanging(value);
					this.SendPropertyChanging();
					this._productid = value;
					this.SendPropertyChanged("productid");
					this.OnproductidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packaging", DbType="NVarChar(50)")]
		public string packaging
		{
			get
			{
				return this._packaging;
			}
			set
			{
				if ((this._packaging != value))
				{
					this.OnpackagingChanging(value);
					this.SendPropertyChanging();
					this._packaging = value;
					this.SendPropertyChanged("packaging");
					this.OnpackagingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="msproduk_detaildelivery", Storage="_detaildeliveries", ThisKey="productid", OtherKey="productid")]
		public EntitySet<detaildelivery> detaildeliveries
		{
			get
			{
				return this._detaildeliveries;
			}
			set
			{
				this._detaildeliveries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="msproduk_detailfaktur", Storage="_detailfakturs", ThisKey="productid", OtherKey="produkid")]
		public EntitySet<detailfaktur> detailfakturs
		{
			get
			{
				return this._detailfakturs;
			}
			set
			{
				this._detailfakturs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detaildeliveries(detaildelivery entity)
		{
			this.SendPropertyChanging();
			entity.msproduk = this;
		}
		
		private void detach_detaildeliveries(detaildelivery entity)
		{
			this.SendPropertyChanging();
			entity.msproduk = null;
		}
		
		private void attach_detailfakturs(detailfaktur entity)
		{
			this.SendPropertyChanging();
			entity.msproduk = this;
		}
		
		private void detach_detailfakturs(detailfaktur entity)
		{
			this.SendPropertyChanging();
			entity.msproduk = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailfaktur")]
	public partial class detailfaktur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _detailfakturid;
		
		private string _fakturid;
		
		private string _produkid;
		
		private System.Nullable<int> _qty;
		
		private System.Nullable<int> _price;
		
		private EntityRef<msproduk> _msproduk;
		
		private EntityRef<headerfaktur> _headerfaktur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndetailfakturidChanging(int value);
    partial void OndetailfakturidChanged();
    partial void OnfakturidChanging(string value);
    partial void OnfakturidChanged();
    partial void OnprodukidChanging(string value);
    partial void OnprodukidChanged();
    partial void OnqtyChanging(System.Nullable<int> value);
    partial void OnqtyChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public detailfaktur()
		{
			this._msproduk = default(EntityRef<msproduk>);
			this._headerfaktur = default(EntityRef<headerfaktur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detailfakturid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int detailfakturid
		{
			get
			{
				return this._detailfakturid;
			}
			set
			{
				if ((this._detailfakturid != value))
				{
					this.OndetailfakturidChanging(value);
					this.SendPropertyChanging();
					this._detailfakturid = value;
					this.SendPropertyChanged("detailfakturid");
					this.OndetailfakturidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fakturid", DbType="NChar(9)")]
		public string fakturid
		{
			get
			{
				return this._fakturid;
			}
			set
			{
				if ((this._fakturid != value))
				{
					if (this._headerfaktur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfakturidChanging(value);
					this.SendPropertyChanging();
					this._fakturid = value;
					this.SendPropertyChanged("fakturid");
					this.OnfakturidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produkid", DbType="NChar(5)")]
		public string produkid
		{
			get
			{
				return this._produkid;
			}
			set
			{
				if ((this._produkid != value))
				{
					if (this._msproduk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnprodukidChanging(value);
					this.SendPropertyChanging();
					this._produkid = value;
					this.SendPropertyChanged("produkid");
					this.OnprodukidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
		public System.Nullable<int> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="msproduk_detailfaktur", Storage="_msproduk", ThisKey="produkid", OtherKey="productid", IsForeignKey=true)]
		public msproduk msproduk
		{
			get
			{
				return this._msproduk.Entity;
			}
			set
			{
				msproduk previousValue = this._msproduk.Entity;
				if (((previousValue != value) 
							|| (this._msproduk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._msproduk.Entity = null;
						previousValue.detailfakturs.Remove(this);
					}
					this._msproduk.Entity = value;
					if ((value != null))
					{
						value.detailfakturs.Add(this);
						this._produkid = value.productid;
					}
					else
					{
						this._produkid = default(string);
					}
					this.SendPropertyChanged("msproduk");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerfaktur_detailfaktur", Storage="_headerfaktur", ThisKey="fakturid", OtherKey="fakturid", IsForeignKey=true)]
		public headerfaktur headerfaktur
		{
			get
			{
				return this._headerfaktur.Entity;
			}
			set
			{
				headerfaktur previousValue = this._headerfaktur.Entity;
				if (((previousValue != value) 
							|| (this._headerfaktur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._headerfaktur.Entity = null;
						previousValue.detailfakturs.Remove(this);
					}
					this._headerfaktur.Entity = value;
					if ((value != null))
					{
						value.detailfakturs.Add(this);
						this._fakturid = value.fakturid;
					}
					else
					{
						this._fakturid = default(string);
					}
					this.SendPropertyChanged("headerfaktur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.headerdelivery")]
	public partial class headerdelivery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DeliveryId;
		
		private string _PONumber;
		
		private string _Place;
		
		private System.Nullable<byte> _Delivered;
		
		private EntitySet<detaildelivery> _detaildeliveries;
		
		private EntityRef<headerpo> _headerpo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeliveryIdChanging(string value);
    partial void OnDeliveryIdChanged();
    partial void OnPONumberChanging(string value);
    partial void OnPONumberChanged();
    partial void OnPlaceChanging(string value);
    partial void OnPlaceChanged();
    partial void OnDeliveredChanging(System.Nullable<byte> value);
    partial void OnDeliveredChanged();
    #endregion
		
		public headerdelivery()
		{
			this._detaildeliveries = new EntitySet<detaildelivery>(new Action<detaildelivery>(this.attach_detaildeliveries), new Action<detaildelivery>(this.detach_detaildeliveries));
			this._headerpo = default(EntityRef<headerpo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryId", DbType="NChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DeliveryId
		{
			get
			{
				return this._DeliveryId;
			}
			set
			{
				if ((this._DeliveryId != value))
				{
					this.OnDeliveryIdChanging(value);
					this.SendPropertyChanging();
					this._DeliveryId = value;
					this.SendPropertyChanged("DeliveryId");
					this.OnDeliveryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONumber", DbType="NVarChar(50)")]
		public string PONumber
		{
			get
			{
				return this._PONumber;
			}
			set
			{
				if ((this._PONumber != value))
				{
					if (this._headerpo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPONumberChanging(value);
					this.SendPropertyChanging();
					this._PONumber = value;
					this.SendPropertyChanged("PONumber");
					this.OnPONumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place", DbType="NVarChar(50)")]
		public string Place
		{
			get
			{
				return this._Place;
			}
			set
			{
				if ((this._Place != value))
				{
					this.OnPlaceChanging(value);
					this.SendPropertyChanging();
					this._Place = value;
					this.SendPropertyChanged("Place");
					this.OnPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delivered", DbType="TinyInt")]
		public System.Nullable<byte> Delivered
		{
			get
			{
				return this._Delivered;
			}
			set
			{
				if ((this._Delivered != value))
				{
					this.OnDeliveredChanging(value);
					this.SendPropertyChanging();
					this._Delivered = value;
					this.SendPropertyChanged("Delivered");
					this.OnDeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerdelivery_detaildelivery", Storage="_detaildeliveries", ThisKey="DeliveryId", OtherKey="deliveryid")]
		public EntitySet<detaildelivery> detaildeliveries
		{
			get
			{
				return this._detaildeliveries;
			}
			set
			{
				this._detaildeliveries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerpo_headerdelivery", Storage="_headerpo", ThisKey="PONumber", OtherKey="PONumber", IsForeignKey=true)]
		public headerpo headerpo
		{
			get
			{
				return this._headerpo.Entity;
			}
			set
			{
				headerpo previousValue = this._headerpo.Entity;
				if (((previousValue != value) 
							|| (this._headerpo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._headerpo.Entity = null;
						previousValue.headerdeliveries.Remove(this);
					}
					this._headerpo.Entity = value;
					if ((value != null))
					{
						value.headerdeliveries.Add(this);
						this._PONumber = value.PONumber;
					}
					else
					{
						this._PONumber = default(string);
					}
					this.SendPropertyChanged("headerpo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detaildeliveries(detaildelivery entity)
		{
			this.SendPropertyChanging();
			entity.headerdelivery = this;
		}
		
		private void detach_detaildeliveries(detaildelivery entity)
		{
			this.SendPropertyChanging();
			entity.headerdelivery = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.headerfaktur")]
	public partial class headerfaktur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _fakturid;
		
		private string _ponumber;
		
		private System.Nullable<int> _custid;
		
		private System.Nullable<System.DateTime> _date;
		
		private EntitySet<detailfaktur> _detailfakturs;
		
		private EntityRef<headerpo> _headerpo;
		
		private EntityRef<mscustomer> _mscustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfakturidChanging(string value);
    partial void OnfakturidChanged();
    partial void OnponumberChanging(string value);
    partial void OnponumberChanged();
    partial void OncustidChanging(System.Nullable<int> value);
    partial void OncustidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public headerfaktur()
		{
			this._detailfakturs = new EntitySet<detailfaktur>(new Action<detailfaktur>(this.attach_detailfakturs), new Action<detailfaktur>(this.detach_detailfakturs));
			this._headerpo = default(EntityRef<headerpo>);
			this._mscustomer = default(EntityRef<mscustomer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fakturid", DbType="NChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fakturid
		{
			get
			{
				return this._fakturid;
			}
			set
			{
				if ((this._fakturid != value))
				{
					this.OnfakturidChanging(value);
					this.SendPropertyChanging();
					this._fakturid = value;
					this.SendPropertyChanged("fakturid");
					this.OnfakturidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ponumber", DbType="NVarChar(50)")]
		public string ponumber
		{
			get
			{
				return this._ponumber;
			}
			set
			{
				if ((this._ponumber != value))
				{
					if (this._headerpo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnponumberChanging(value);
					this.SendPropertyChanging();
					this._ponumber = value;
					this.SendPropertyChanged("ponumber");
					this.OnponumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custid", DbType="Int")]
		public System.Nullable<int> custid
		{
			get
			{
				return this._custid;
			}
			set
			{
				if ((this._custid != value))
				{
					if (this._mscustomer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncustidChanging(value);
					this.SendPropertyChanging();
					this._custid = value;
					this.SendPropertyChanged("custid");
					this.OncustidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerfaktur_detailfaktur", Storage="_detailfakturs", ThisKey="fakturid", OtherKey="fakturid")]
		public EntitySet<detailfaktur> detailfakturs
		{
			get
			{
				return this._detailfakturs;
			}
			set
			{
				this._detailfakturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerpo_headerfaktur", Storage="_headerpo", ThisKey="ponumber", OtherKey="PONumber", IsForeignKey=true)]
		public headerpo headerpo
		{
			get
			{
				return this._headerpo.Entity;
			}
			set
			{
				headerpo previousValue = this._headerpo.Entity;
				if (((previousValue != value) 
							|| (this._headerpo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._headerpo.Entity = null;
						previousValue.headerfakturs.Remove(this);
					}
					this._headerpo.Entity = value;
					if ((value != null))
					{
						value.headerfakturs.Add(this);
						this._ponumber = value.PONumber;
					}
					else
					{
						this._ponumber = default(string);
					}
					this.SendPropertyChanged("headerpo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mscustomer_headerfaktur", Storage="_mscustomer", ThisKey="custid", OtherKey="custid", IsForeignKey=true)]
		public mscustomer mscustomer
		{
			get
			{
				return this._mscustomer.Entity;
			}
			set
			{
				mscustomer previousValue = this._mscustomer.Entity;
				if (((previousValue != value) 
							|| (this._mscustomer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mscustomer.Entity = null;
						previousValue.headerfakturs.Remove(this);
					}
					this._mscustomer.Entity = value;
					if ((value != null))
					{
						value.headerfakturs.Add(this);
						this._custid = value.custid;
					}
					else
					{
						this._custid = default(Nullable<int>);
					}
					this.SendPropertyChanged("mscustomer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailfakturs(detailfaktur entity)
		{
			this.SendPropertyChanging();
			entity.headerfaktur = this;
		}
		
		private void detach_detailfakturs(detailfaktur entity)
		{
			this.SendPropertyChanging();
			entity.headerfaktur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.headerpo")]
	public partial class headerpo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PONumber;
		
		private System.Nullable<int> _custid;
		
		private System.Nullable<System.DateTime> _date;
		
		private EntitySet<headerdelivery> _headerdeliveries;
		
		private EntitySet<headerfaktur> _headerfakturs;
		
		private EntityRef<mscustomer> _mscustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPONumberChanging(string value);
    partial void OnPONumberChanged();
    partial void OncustidChanging(System.Nullable<int> value);
    partial void OncustidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public headerpo()
		{
			this._headerdeliveries = new EntitySet<headerdelivery>(new Action<headerdelivery>(this.attach_headerdeliveries), new Action<headerdelivery>(this.detach_headerdeliveries));
			this._headerfakturs = new EntitySet<headerfaktur>(new Action<headerfaktur>(this.attach_headerfakturs), new Action<headerfaktur>(this.detach_headerfakturs));
			this._mscustomer = default(EntityRef<mscustomer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PONumber
		{
			get
			{
				return this._PONumber;
			}
			set
			{
				if ((this._PONumber != value))
				{
					this.OnPONumberChanging(value);
					this.SendPropertyChanging();
					this._PONumber = value;
					this.SendPropertyChanged("PONumber");
					this.OnPONumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custid", DbType="Int")]
		public System.Nullable<int> custid
		{
			get
			{
				return this._custid;
			}
			set
			{
				if ((this._custid != value))
				{
					if (this._mscustomer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncustidChanging(value);
					this.SendPropertyChanging();
					this._custid = value;
					this.SendPropertyChanged("custid");
					this.OncustidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerpo_headerdelivery", Storage="_headerdeliveries", ThisKey="PONumber", OtherKey="PONumber")]
		public EntitySet<headerdelivery> headerdeliveries
		{
			get
			{
				return this._headerdeliveries;
			}
			set
			{
				this._headerdeliveries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="headerpo_headerfaktur", Storage="_headerfakturs", ThisKey="PONumber", OtherKey="ponumber")]
		public EntitySet<headerfaktur> headerfakturs
		{
			get
			{
				return this._headerfakturs;
			}
			set
			{
				this._headerfakturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mscustomer_headerpo", Storage="_mscustomer", ThisKey="custid", OtherKey="custid", IsForeignKey=true)]
		public mscustomer mscustomer
		{
			get
			{
				return this._mscustomer.Entity;
			}
			set
			{
				mscustomer previousValue = this._mscustomer.Entity;
				if (((previousValue != value) 
							|| (this._mscustomer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mscustomer.Entity = null;
						previousValue.headerpos.Remove(this);
					}
					this._mscustomer.Entity = value;
					if ((value != null))
					{
						value.headerpos.Add(this);
						this._custid = value.custid;
					}
					else
					{
						this._custid = default(Nullable<int>);
					}
					this.SendPropertyChanged("mscustomer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_headerdeliveries(headerdelivery entity)
		{
			this.SendPropertyChanging();
			entity.headerpo = this;
		}
		
		private void detach_headerdeliveries(headerdelivery entity)
		{
			this.SendPropertyChanging();
			entity.headerpo = null;
		}
		
		private void attach_headerfakturs(headerfaktur entity)
		{
			this.SendPropertyChanging();
			entity.headerpo = this;
		}
		
		private void detach_headerfakturs(headerfaktur entity)
		{
			this.SendPropertyChanging();
			entity.headerpo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mscustomer")]
	public partial class mscustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _custid;
		
		private string _name;
		
		private string _address;
		
		private string _handphone;
		
		private EntitySet<headerfaktur> _headerfakturs;
		
		private EntitySet<headerpo> _headerpos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncustidChanging(int value);
    partial void OncustidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnhandphoneChanging(string value);
    partial void OnhandphoneChanged();
    #endregion
		
		public mscustomer()
		{
			this._headerfakturs = new EntitySet<headerfaktur>(new Action<headerfaktur>(this.attach_headerfakturs), new Action<headerfaktur>(this.detach_headerfakturs));
			this._headerpos = new EntitySet<headerpo>(new Action<headerpo>(this.attach_headerpos), new Action<headerpo>(this.detach_headerpos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int custid
		{
			get
			{
				return this._custid;
			}
			set
			{
				if ((this._custid != value))
				{
					this.OncustidChanging(value);
					this.SendPropertyChanging();
					this._custid = value;
					this.SendPropertyChanged("custid");
					this.OncustidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handphone", DbType="NVarChar(50)")]
		public string handphone
		{
			get
			{
				return this._handphone;
			}
			set
			{
				if ((this._handphone != value))
				{
					this.OnhandphoneChanging(value);
					this.SendPropertyChanging();
					this._handphone = value;
					this.SendPropertyChanged("handphone");
					this.OnhandphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mscustomer_headerfaktur", Storage="_headerfakturs", ThisKey="custid", OtherKey="custid")]
		public EntitySet<headerfaktur> headerfakturs
		{
			get
			{
				return this._headerfakturs;
			}
			set
			{
				this._headerfakturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mscustomer_headerpo", Storage="_headerpos", ThisKey="custid", OtherKey="custid")]
		public EntitySet<headerpo> headerpos
		{
			get
			{
				return this._headerpos;
			}
			set
			{
				this._headerpos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_headerfakturs(headerfaktur entity)
		{
			this.SendPropertyChanging();
			entity.mscustomer = this;
		}
		
		private void detach_headerfakturs(headerfaktur entity)
		{
			this.SendPropertyChanging();
			entity.mscustomer = null;
		}
		
		private void attach_headerpos(headerpo entity)
		{
			this.SendPropertyChanging();
			entity.mscustomer = this;
		}
		
		private void detach_headerpos(headerpo entity)
		{
			this.SendPropertyChanging();
			entity.mscustomer = null;
		}
	}
}
#pragma warning restore 1591
