<?xml version="1.0" encoding="utf-8"?><Database Name="test" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=desktop-raclv28\sqlexpress;Initial Catalog=test;Integrated Security=True" SettingsObjectName="OutlineExample.Properties.Settings" SettingsPropertyName="testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="roleid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Role_User" Member="Role" ThisKey="roleid" OtherKey="id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="namarole" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Role_User" Member="Users" ThisKey="id" OtherKey="roleid" Type="User" />
    </Type>
  </Table>
</Database>